### ISSUE TITLE
Shell connecting stuck 

### ISSUE THREAD

**Issue by mjgritli** [0blio/caesarRAT#11] opened 2019-04-15 16:06 UTC
Dear all...
I was able to set up Caesar and receive the target in my list.
however, upon selecting the target and issuing shell, it only stays as connecting...
any clue what to do?
the target pc is a a Win10 VM in my lab. It's powered on and working but still appearing as a red icon under the online flag 
regards

**Comment by 0blio** [comment] 2019-04-19 08:03
Hi,
did you compiled the payload with PyInstaller?
If yes, try to run it only with Python, I think the problem is you don't have libraries installed..

I'm working on a more stable version of the payload these days, it will be in C++.

**Comment by mjgritli** [comment] 2019-04-20 11:57
well noted,
I'll try doing that, although I tried with PyInstaller & Python as well.
the computer still appears as offline, although I see it in sessions.
Will try and get back to you.
Thanks for your reply.

-- Kind Regards --
Mohammed J Gritli
Network/Security Engineer | Web Developer
Mobile: +218927388807
LinkedIn: mjgritli ,twitter : @mjgritli, Skype: mjgritli
P Save a tree. Don't print this e-mail unless it's really necessary

**Comment by 0blio** [comment] 2019-04-21 16:20
I managed to add a PS in the pyinstaller section of the wiki.
You can find it here: https://github.com/0blio/caesarRAT/wiki/Compile-client-to-executable

In order to correctly compile the payload you have to install the following libraries on the compiler machine:

- requests
- grequests

Once you have the .exe ready, you can port it where you want to.

**Comment by 0blio** [comment] 2019-06-04 17:19
Solved.

**Closed by 0blio** 2019-06-04 17:19 UTC
